Implement yust_file_service_dart.dart
univelop/yust pull request #253
Opened 2023-06-29 18:22 UTC by janiswehen

2023-07-03 13:33 UTC, CLNMR requested changes
Ich hab ein paar kleine Änderungen direkt umgesetzt. Folgende Sachen sind mir noch aufgefallen:
1. Dokumentation der öffentlichen API (also der öffentlichen Funktionen) fehlt noch

Hast du schon nen Tool oder so geschrieben, um das zu testen?

2023-07-03 13:33 UTC, CLNMR commented on lib/src/services/yust_file_service_dart.dart
> +          completer.complete(bytesBuilder.takeBytes());
Warum brauchen wir diese Zeile, und Z77-79?

2023-07-03 15:22 UTC, janiswehen commented
Hier ist der Code für ein Tool, mit dem man den `FileService` testen kann:
```dart
import 'package:yust/yust.dart';

import '../helpers/session_helpers.dart';

Future<void> testFileService([String? workspaceId]) async {
  final sessionController = await initSessionController();
  await forEachWorkspace(sessionController, workspaceId, (workspace) async {
    // Insert path to file
    const path = 'path/to';
    const name = 'file';
    const cpPath = 'test/copy';
    const cpName = 'image.jpeg';
    final bytes = await Yust.fileService.downloadFile(path: path, name: name);
    print(await Yust.fileService
        .uploadFile(path: cpPath, name: cpName, bytes: bytes));
    print(await Yust.fileService.fileExist(path: cpPath, name: cpName));
    print(
        await Yust.fileService.getFileDownloadUrl(path: cpPath, name: cpName));
    await Yust.fileService.deleteFile(path: cpPath, name: cpName);
    print(await Yust.fileService.fileExist(path: cpPath, name: cpName));
  });
}

```

2023-07-06 21:33 UTC, janneskoehler approved these changes

2023-07-06 21:38 UTC, merged