implement sum and avg for database flutter
univelop/yust pull request #324
Opened 2024-07-11 09:57 UTC by janiswehen

2024-07-11 17:27 UTC, CLNMR approved these changes

2024-07-18 12:50 UTC, sinnaj-r requested changes

2024-07-18 12:50 UTC, sinnaj-r commented on lib/src/services/yust_database_service_flutter.dart
> +    final snapshot = await query.aggregate(cf.average(fieldPath)).get();
I don't think you need `cf` here.
Also can you test if this works with fieldPaths containing numeric parts, e.g. `test.01234test`

2024-07-26 22:22 UTC, janneskoehler approved these changes

2024-07-26 22:22 UTC, merged